Repository oasisprotocol/oasis-web3-gateway, pull requests merged in 2024-03, with the labels that each got.

#538 Add local development debugging instructions
  docker/README.md
Labels: documentation, docs

#547 fix: go 1.22.1 fixes 'toolchain not available'
  go.mod
Labels: bug, c:deps

#550 feat: sapphire 0.7.2-testnet
  docker/sapphire-localnet/Dockerfile
  go.mod
  go.sum
Labels: p:1, c:deps, docker, tests
